server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.189.110
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.189.110
ly:
  sms:
    accessKeyId: LTAI4GE1y3GY6Jv7YTgoiQpM # 自己的accessKeyId
    accessKeySecret: V04CVJ7IPQJ9X4xAirghjKLWk3wbs4 # 自己的accessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_190282710 # 模板名称